import fs from 'fs-extra';
import path from 'path';

const nexusWorkflow = `name: Nexus Complete Pipeline

on:
  push:
    branches: [main, master, develop]
  schedule:
    - cron: '0 7 * * *'  # Daily at 7 AM UTC
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - analyze
          - remind
          - scout

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      should-analyze: \${{ steps.check.outputs.analyze }}
      should-remind: \${{ steps.check.outputs.remind }}
      should-scout: \${{ steps.check.outputs.scout }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Determine actions needed
        id: check
        run: |
          # Check if PRD or code changed
          if git diff HEAD~1 --name-only 2>/dev/null | grep -E "(PRD\\.md|\\.js$|\\.py$|\\.ts$)"; then
            echo "analyze=true" >> $GITHUB_OUTPUT
          fi
          
          # Check last commit age
          LAST_COMMIT=$(git log -1 --format="%ct" 2>/dev/null || echo 0)
          CURRENT=$(date +%s)
          DAYS=$(( ($CURRENT - $LAST_COMMIT) / 86400 ))
          
          if [ $DAYS -ge 5 ]; then
            echo "remind=true" >> $GITHUB_OUTPUT
          fi
          
          # Check for new modules
          if git diff HEAD~1 --name-only 2>/dev/null | grep "modules/"; then
            echo "scout=true" >> $GITHUB_OUTPUT
          fi

  analyze:
    needs: setup
    if: needs.setup.outputs.should-analyze == 'true' || github.event.inputs.action == 'analyze' || github.event.inputs.action == 'all'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Nexus CLI
        run: |
          npm install -g nexus-cli || npm install -g ./cli
      
      - name: Run analysis
        id: analysis
        run: |
          nexus analyze --output json > analysis.json
          
          # Extract summary
          HIGH=$(jq '.issues.high | length' analysis.json)
          MEDIUM=$(jq '.issues.medium | length' analysis.json)
          LOW=$(jq '.issues.low | length' analysis.json)
          
          echo "high_issues=$HIGH" >> $GITHUB_OUTPUT
          echo "medium_issues=$MEDIUM" >> $GITHUB_OUTPUT
          echo "low_issues=$LOW" >> $GITHUB_OUTPUT
      
      - name: Create issue if high priority issues found
        if: steps.analysis.outputs.high_issues > 0
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const analysis = JSON.parse(fs.readFileSync('analysis.json', 'utf8'));
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: \`🔴 Code-PRD drift: \${analysis.issues.high.length} critical issues\`,
              body: \`## Urgent: Code implementation differs from PRD
              
              ### High Priority Issues
              \${analysis.issues.high.map(issue => \`- \${issue.title}\`).join('\\n')}
              
              ### Summary
              - High Priority: \${analysis.issues.high.length}
              - Medium Priority: \${analysis.issues.medium.length}
              - Low Priority: \${analysis.issues.low.length}
              
              [View full report](reports/code-sync-report.md)
              
              ---
              *Generated by Project Nexus*\`,
              labels: ['drift', 'high-priority', 'automated']
            });

  remind:
    needs: setup
    if: needs.setup.outputs.should-remind == 'true' || github.event.inputs.action == 'remind' || github.event.inputs.action == 'all'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Calculate inactivity
        id: inactivity
        run: |
          LAST_COMMIT=$(git log -1 --format="%ct" 2>/dev/null || echo 0)
          LAST_MESSAGE=$(git log -1 --format="%s" 2>/dev/null || echo "No commits")
          LAST_AUTHOR=$(git log -1 --format="%an" 2>/dev/null || echo "Unknown")
          CURRENT=$(date +%s)
          DAYS=$(( ($CURRENT - $LAST_COMMIT) / 86400 ))
          
          echo "days=$DAYS" >> $GITHUB_OUTPUT
          echo "last_message=$LAST_MESSAGE" >> $GITHUB_OUTPUT
          echo "last_author=$LAST_AUTHOR" >> $GITHUB_OUTPUT
      
      - name: Extract next steps from PRD
        id: next_steps
        run: |
          if grep -q "## Next Steps" PRD.md 2>/dev/null; then
            NEXT_STEPS=$(awk '/## Next Steps/,/^##[^#]/' PRD.md | head -20)
          else
            NEXT_STEPS="No next steps defined in PRD"
          fi
          
          echo "steps<<EOF" >> $GITHUB_OUTPUT
          echo "$NEXT_STEPS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Create reminder issue
        uses: actions/github-script@v6
        with:
          script: |
            const title = \`⏰ Project inactive for \${{ steps.inactivity.outputs.days }} days\`;
            
            const body = \`## Project Activity Reminder
            
            This project has been inactive for **\${{ steps.inactivity.outputs.days }} days**.
            
            ### Last Activity
            - **Last Commit:** "\${{ steps.inactivity.outputs.last_message }}"
            - **Last Author:** \${{ steps.inactivity.outputs.last_author }}
            
            ### Next Steps from PRD
            \${{ steps.next_steps.outputs.steps }}
            
            ### Quick Actions
            - [ ] Review current status: \\\`nexus status\\\`
            - [ ] Import recent conversations: \\\`nexus import conversation\\\`
            - [ ] Run analysis: \\\`nexus analyze\\\`
            - [ ] Continue development
            - [ ] Or archive project if no longer needed
            
            ---
            *This reminder was automatically generated by Project Nexus*\`;
            
            // Check if reminder already exists
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'reminder,inactive',
              state: 'open'
            });
            
            if (issues.data.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['reminder', 'inactive', 'automated']
              });
            }

  scout:
    needs: setup
    if: needs.setup.outputs.should-scout == 'true' || github.event.inputs.action == 'scout' || github.event.inputs.action == 'all'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Nexus CLI
        run: |
          npm install -g nexus-cli || npm install -g ./cli
      
      - name: Run module scout
        id: scout
        run: |
          nexus scout --output json > suggestions.json
          COUNT=$(jq '. | length' suggestions.json)
          echo "count=$COUNT" >> $GITHUB_OUTPUT
      
      - name: Create suggestion issue
        if: steps.scout.outputs.count > 0
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const suggestions = JSON.parse(fs.readFileSync('suggestions.json', 'utf8'));
            
            let body = \`## 🎯 Module Reuse Opportunities Found
            
            Project Nexus Scout found **\${suggestions.length}** modules that could be reused:
            
            ### Suggestions
            \`;
            
            suggestions.forEach((s, i) => {
              body += \`
            \${i + 1}. **\${s.module}**
               - From: \\\`\${s.source_project}\\\`
               - Similarity: \${s.similarity}%
               - Time saved: ~\${s.time_saved} hours
            \`;
            });
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: \`♻️ \${suggestions.length} reusable modules found\`,
              body: body,
              labels: ['enhancement', 'reuse', 'automated']
            });

  summary:
    needs: [analyze, remind, scout]
    if: always()
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate workflow summary
        run: |
          echo "## 📊 Nexus Pipeline Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "\${{ needs.analyze.result }}" == "success" ]; then
            echo "✅ **Analysis:** Completed successfully" >> $GITHUB_STEP_SUMMARY
          elif [ "\${{ needs.analyze.result }}" == "skipped" ]; then
            echo "⏭️ **Analysis:** Skipped (no changes detected)" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Analysis:** Failed or not run" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "\${{ needs.remind.result }}" == "success" ]; then
            echo "✅ **Reminder:** Created/Updated" >> $GITHUB_STEP_SUMMARY
          elif [ "\${{ needs.remind.result }}" == "skipped" ]; then
            echo "⏭️ **Reminder:** Skipped (project active)" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Reminder:** Failed or not run" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "\${{ needs.scout.result }}" == "success" ]; then
            echo "✅ **Scout:** Module suggestions generated" >> $GITHUB_STEP_SUMMARY
          elif [ "\${{ needs.scout.result }}" == "skipped" ]; then
            echo "⏭️ **Scout:** Skipped (no new modules)" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Scout:** Failed or not run" >> $GITHUB_STEP_SUMMARY
          fi
`;

export async function createGitHubWorkflows(projectPath: string): Promise<void> {
  const workflowsDir = path.join(projectPath, '.github', 'workflows');
  
  // Ensure workflows directory exists
  await fs.ensureDir(workflowsDir);
  
  // Write main Nexus workflow
  const nexusWorkflowPath = path.join(workflowsDir, 'nexus.yml');
  await fs.writeFile(nexusWorkflowPath, nexusWorkflow);
  
  // Create PR workflow
  const prWorkflow = createPRWorkflow();
  const prWorkflowPath = path.join(workflowsDir, 'nexus-pr.yml');
  await fs.writeFile(prWorkflowPath, prWorkflow);
}

function createPRWorkflow(): string {
  return `name: Nexus PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Nexus CLI
        run: |
          npm install -g nexus-cli || npm install -g ./cli
      
      - name: Check PRD updates
        run: |
          # Check if PRD needs updating based on code changes
          nexus analyze --pr-mode
      
      - name: Post comment with analysis
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            if (fs.existsSync('pr-analysis.md')) {
              const analysis = fs.readFileSync('pr-analysis.md', 'utf8');
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: analysis
              });
            }
`;
}


